### ISSUE TITLE
[Bug]: using mace with dispersion results in crasg

### ISSUE THREAD

**Issue by alinelena** [materialsvirtuallab/matcalc#14]
### Email (Optional)

alinm.elena@gmail.com

### Version

v2023.11

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

using mace as calculator with dispersion=True results in 

```
)
  cell: Optional[Tensor] = torch.tensor(
Traceback (most recent call last):
  File "/work4/scd/scarf562/ml/LiFePO4/./LiFePO4-NEB.py", line 89, in <module>
    NEBcalc = NEBCalc.from_end_images(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work4/scd/scarf562/micromamba/micromamba/envs/mace/lib/python3.11/site-packages/matcalc/neb.py", line 110, in from_end_images
    return cls(images=images, calculator=calculator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work4/scd/scarf562/micromamba/micromamba/envs/mace/lib/python3.11/site-packages/matcalc/neb.py", line 65, in __init__
    atoms.calc = get_universal_calculator(self.calculator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work4/scd/scarf562/micromamba/micromamba/envs/mace/lib/python3.11/site-packages/matcalc/util.py", line 40, in get_universal_calculator
    if name.lower().startswith("m3gnet"):
       ^^^^^^^^^^
AttributeError: 'SumCalculator' object has no attribute 'lower'
```

### Code snippet

```python
calculator_mace = get_universal_calculator("mace",model="large",  default_dtype="float64",dispersion=True)
```
```


### Log output

```shell
Traceback (most recent call last):
  File "/work4/scd/scarf562/ml/LiFePO4/./LiFePO4-NEB.py", line 89, in <module>
    NEBcalc = NEBCalc.from_end_images(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work4/scd/scarf562/micromamba/micromamba/envs/mace/lib/python3.11/site-packages/matcalc/neb.py", line 110, in from_end_images
    return cls(images=images, calculator=calculator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work4/scd/scarf562/micromamba/micromamba/envs/mace/lib/python3.11/site-packages/matcalc/neb.py", line 65, in __init__
    atoms.calc = get_universal_calculator(self.calculator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work4/scd/scarf562/micromamba/micromamba/envs/mace/lib/python3.11/site-packages/matcalc/util.py", line 40, in get_universal_calculator
    if name.lower().startswith("m3gnet"):
       ^^^^^^^^^^
AttributeError: 'SumCalculator' object has no attribute 'lower'
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janosh** [comment]
Thanks for reporting @alinelena! 👍 This is an easy fix.
